server:
  port: 2002
spring:
  application:
    name: sp-movie-ribbon
# 使用Ribbon 实现负载均衡，即不需要配置 服务者的URL，通过 eureka注册中心获取
#user:
#  userServicePath: http://localhost:1000/user/
eureka:
  client:
    #实现健康检查开关，需要依赖：spring-boot-actuator
    healthcheck:
        enabled: true
    serviceUrl:
      #registered-replicas	http://localhost:8761/eureka/
      #unavailable-replicas	http://localhost:8761/eureka/,
      #defaultZone: http://localhost:8761/eureka/                  #将当前应用，注册到指定eureka 服务器中
      defaultZone: http://root:root123456@localhost:8761/eureka/   #将当前应用，注册到指定eureka 服务器中【安全认证方式】
  instance:
    # 默认是使用，主机名进行访问，若以IP访问，需要将  prefer-ip-address: true
    prefer-ip-address: true
    # Eureka Instance ID
    # 默认：${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}}.
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}}.